apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5433
    user: grafana_ro
    database: labdb
    jsonData:
      sslmode: disable
    secureJsonData:
      password: "${GRAFANA_POSTGRES_RO_PASSWORD}"  # From .env
    version: 1
    editable: false
